package gov.nih.nci.cananolab.domain.particle;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import gov.nih.nci.cananolab.domain.common.Protocol;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SynthesisPurification generated by hbm2java
 */
public class SynthesisPurification implements java.io.Serializable {

	private long synthesisFuncPurificationPkId;
	private Protocol protocol;
	private SynthesisFunctionalization synthesisFunctionalization;
	private String type;
	private String methodName;
	private String designMethodDescription;
	private String createdBy;
	private Date createdDate;
	private Integer yield;
	private Set purities = new HashSet(0);
	private Set purificationConfigs = new HashSet(0);

	public SynthesisPurification() {
	}

	public SynthesisPurification(long synthesisFuncPurificationPkId, Protocol protocol,
			SynthesisFunctionalization synthesisFunctionalization, String createdBy, Date createdDate) {
		this.synthesisFuncPurificationPkId = synthesisFuncPurificationPkId;
		this.protocol = protocol;
		this.synthesisFunctionalization = synthesisFunctionalization;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public SynthesisPurification(long synthesisFuncPurificationPkId, Protocol protocol,
			SynthesisFunctionalization synthesisFunctionalization, String type, String methodName,
			String designMethodDescription, String createdBy, Date createdDate, Set purities, Set purificationConfigs, Integer yield) {
		this.synthesisFuncPurificationPkId = synthesisFuncPurificationPkId;
		this.protocol = protocol;
		this.synthesisFunctionalization = synthesisFunctionalization;
		this.type = type;
		this.methodName = methodName;
		this.designMethodDescription = designMethodDescription;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.purities = purities;
		this.purificationConfigs = purificationConfigs;
		this.yield = yield;
	}

	public long getId() {
		return this.synthesisFuncPurificationPkId;
	}

	public void setId(long synthesisFuncPurificationPkId) {
		this.synthesisFuncPurificationPkId = synthesisFuncPurificationPkId;
	}

	public Protocol getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Protocol protocol) {
		this.protocol = protocol;
	}

	public SynthesisFunctionalization getSynthesisFunctionalization() {
		return this.synthesisFunctionalization;
	}

	public void setSynthesisFunctionalization(SynthesisFunctionalization synthesisFunctionalization) {
		this.synthesisFunctionalization = synthesisFunctionalization;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	public String getDesignMethodDescription() {
		return this.designMethodDescription;
	}

	public void setDesignMethodDescription(String designMethodDescription) {
		this.designMethodDescription = designMethodDescription;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set getPurities() {
		return this.purities;
	}

	public void setPurities(Set purities) {
		this.purities = purities;
	}

	public Set getPurificationConfigs() {
		return this.purificationConfigs;
	}

	public void setPurificationConfigs(Set purificationConfigs) {
		this.purificationConfigs = purificationConfigs;
	}

	public void setYield(Integer yield) {this.yield = yield;}

	public Integer getYield(){return yield;}

}
