package gov.nih.nci.cananolab.domain.particle;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import gov.nih.nci.cananolab.domain.common.Protocol;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SynthesisMaterials generated by hbm2java
 */
public class SynthesisMaterials implements java.io.Serializable {

	private long synthesisMaterialsPkId;
	private Protocol protocol;
	private Synthesis synthesis;
	private String description;
	private Date createdDate;
	private String createdBy;
	private String type;
	private Set synthesisMaterialElements = new HashSet(0);

	public SynthesisMaterials() {
	}

	public SynthesisMaterials(long synthesisMaterialsPkId, Synthesis synthesis, Date createdDate, String createdBy) {
		this.synthesisMaterialsPkId = synthesisMaterialsPkId;
		this.synthesis = synthesis;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public SynthesisMaterials(long synthesisMaterialsPkId, Protocol protocol, Synthesis synthesis, String description,
			Date createdDate, String createdBy, String type, Set synthesisMaterialElements) {
		this.synthesisMaterialsPkId = synthesisMaterialsPkId;
		this.protocol = protocol;
		this.synthesis = synthesis;
		this.description = description;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.type = type;
		this.synthesisMaterialElements = synthesisMaterialElements;
	}

	public long getId() {
		return this.synthesisMaterialsPkId;
	}

	public void setId(long synthesisMaterialsPkId) {
		this.synthesisMaterialsPkId = synthesisMaterialsPkId;
	}

	public Protocol getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Protocol protocol) {
		this.protocol = protocol;
	}

	public Synthesis getSynthesis() {
		return this.synthesis;
	}

	public void setSynthesis(Synthesis synthesis) {
		this.synthesis = synthesis;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getSynthesisMaterialElements() {
		return this.synthesisMaterialElements;
	}

	public void setSynthesisMaterialElements(Set synthesisMaterialElements) {
		this.synthesisMaterialElements = synthesisMaterialElements;
	}

}
