package gov.nih.nci.cananolab.domain.particle;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;


/**
 * Synthesis generated by hbm2java
 */
public class Synthesis implements java.io.Serializable {

	private long synthesisPkId;
	private Sample sample;
	private Set synthesisMaterials = new HashSet(0);
	private Set files = new HashSet(0);
	private Set synthesisFunctionalizations = new HashSet(0);

	public Synthesis() {
	}

	public Synthesis(long synthesisPkId, Sample sample) {
		this.synthesisPkId = synthesisPkId;
		this.sample = sample;
	}

	public Synthesis(long synthesisPkId, Sample sample, Set synthesisMaterials, Set files,
			Set synthesisFunctionalizations) {
		this.synthesisPkId = synthesisPkId;
		this.sample = sample;
		this.synthesisMaterials = synthesisMaterials;
		this.files = files;
		this.synthesisFunctionalizations = synthesisFunctionalizations;
	}

	public long getId() {
		return this.synthesisPkId;
	}

	public void setId(long synthesisPkId) {
		this.synthesisPkId = synthesisPkId;
	}

	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	public Set getSynthesisMaterials() {
		return this.synthesisMaterials;
	}

	public void setSynthesisMaterials(Set synthesisMaterials) {
		this.synthesisMaterials = synthesisMaterials;
	}

	public Set getFiles() {
		return this.files;
	}

	public void setFiles(Set files) {
		this.files = files;
	}

	public Set getSynthesisFunctionalizations() {
		return this.synthesisFunctionalizations;
	}

	public void setSynthesisFunctionalizations(Set synthesisFunctionalizations) {
		this.synthesisFunctionalizations = synthesisFunctionalizations;
	}

}
