package gov.nih.nci.cananolab.domain.particle;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import gov.nih.nci.cananolab.domain.common.File;
import gov.nih.nci.cananolab.domain.common.PurityDatum;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.beans.factory.config.CustomEditorConfigurer;

/**
 * Purity generated by hbm2java
 */
public class SynthesisPurity implements java.io.Serializable {

	private Long purityPkId;
	private Long synthesisPurificationId;
	private SynthesisPurification synthesisPurification;
	private String createdBy;
	private Date createdDate;
	private Set<File> files = new HashSet<File>(0);
	private Set<PurityDatum> purityDatumCollection = new HashSet<PurityDatum>(0);

	public SynthesisPurity() {
	}

	public SynthesisPurity(long purityPkId, Long synthesisPurificationId, String createdBy,
						   Date createdDate, Set files, Set purityDatums) {
		this.purityPkId = purityPkId;
		this.synthesisPurificationId = synthesisPurificationId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.files = files;
		this.purityDatumCollection = purityDatums;
	}

	public Long getId() {
		return this.purityPkId;
	}

	public Long getSynthesisPurificationId() {
		return synthesisPurificationId;
	}

	public void setId(Long purityPkId) {
		this.purityPkId = purityPkId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	public Set<PurityDatum> getPurityDatumCollection() {
		return this.purityDatumCollection;
	}

	public void setPurityDatumCollection(Set<PurityDatum> purityDatums) {
		this.purityDatumCollection = purityDatums;
	}

	public void setSynthesisPurificationId(Long synthesisPurificationId) {
		this.synthesisPurificationId = synthesisPurificationId;
	}
}
