version: 2.1
commands:
  deployment_setup:
    steps:
      - run:
          name: "Set the Tier"
          command: |
            TIER=DEV
            if [[ ${CIRCLE_BRANCH} =~ (prod|uat|test).* ]]; then
              TIER=$(awk -F[\-_] '{print toupper($1)}' \<<< ${CIRCLE_BRANCH})
            fi
            echo "export TIER=${TIER}" >> $BASH_ENV
            echo "Tier was identified as ${TIER} for branch ${CIRCLE_BRANCH}"
      - run:
          name: "Assign Project-level vars"
          command: |
            if [ ! -f deployment.key.json ]; then
              echo "Deployment JSON keyfile not found - loading from CircleCI."
              KEY=${DEPLOYMENT_KEY_ISB_CANANO_DEV}
            else
              echo "Deployment JSON keyfile found."
              KEY="NA"
            fi
            CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CANANO_DEV}
            PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CANANO_DEV}
            BUCKET=${DEPLOYMENT_BUCKET_ISB_CANANO_DEV}
            if [[ ${TIER} == "PROD" ]]; then
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CANANO_PROD}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CANANO_PROD}
              BUCKET=${DEPLOYMENT_BUCKET_ISB_CANANO_PROD}
              KEY=${DEPLOYMENT_KEY_ISB_CANANO_PROD}
            elif [[ ${TIER} == "UAT" ]]; then
              KEY=${DEPLOYMENT_KEY_ISB_CANANO_UAT}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CANANO_UAT}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CANANO_UAT}
              BUCKET=${DEPLOYMENT_BUCKET_ISB_CANANO_UAT}
            elif [[ ${TIER} == "TEST" ]]; then
              KEY=${DEPLOYMENT_KEY_ISB_CANANO_TEST}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CANANO_TEST}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CANANO_TEST}
              BUCKET=${DEPLOYMENT_BUCKET_ISB_CANANO_TEST}
            elif [[ ${TIER} == "DEV" ]]; then
              echo "Using default deployment configuration for tier ${TIER}"
            else
              echo "[ERROR] - Unrecognized tier: ${TIER} - exitng."
              exit 1
            fi

            echo "export DEPLOYMENT_KEY=\"${KEY}\"" >> $BASH_ENV
            echo "export DEPLOYMENT_CLIENT_EMAIL=${CLIENT_EMAIL}" >> $BASH_ENV
            echo "export DEPLOYMENT_PROJECT_ID=${PROJECT_ID}" >> $BASH_ENV
            echo "export DEPLOYMENT_BUCKET=${BUCKET}" >> $BASH_ENV

  deployment_config:
    steps:
      - run:
          name: "Set tier-specific configuration file"
          command: |
            sudo -E /bin/bash ./shell/pull-config.sh
            xargs -a deployment_config.txt -I{} echo "export {}" >> $BASH_ENV

  auth:
    steps:
      - run:
          name: "Service Account Auth and Project Settings"
          command: |
            sudo -E /bin/bash ./shell/gcloud-authentication.sh

  install_cloud_sdk:
    steps:
      - run:
          name: "Install CloudSDK and Java components"
          command: |
            echo "export CLOUDSDK_CORE_DISABLE_PROMPTS=1" >> $BASH_ENV
            sudo apt-get update -qq
            sudo apt-get install ca-certificates python3-distutils apt-transport-https gnupg
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update -qq
            sudo apt-get -y install google-cloud-sdk google-cloud-sdk-app-engine-java
jobs:
  build_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    working_directory: ~/cananolab
    docker:
      - image: cimg/openjdk:8.0.302
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_USER: ubuntu
          MYSQL_PASSWORD: "isb"
          MYSQL_ROOT_PASSWORD: "isb"
    steps:
      - checkout
      - run:
          name: Fix for bug with Git and Ubuntu 20+
          command: |
            SHA=$(git rev-list -1 HEAD)
            echo "export APP_SHA=${SHA:0:7}" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: |
            sudo -E /bin/bash ./shell/install-deps.sh
      - install_cloud_sdk
      - deployment_setup
      - auth
      - deployment_config
      - run:
          name: Staging
          command: |
            sudo -E /bin/bash ./shell/gcloud-pull-staging-files.sh
      - run:
          name: Build
          command: |
            sudo -E /bin/bash ./shell/run-build.sh
      - save_cache:
          key: isb-canano-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
          paths:
            - ./staged
            - ./shell
            - ./NOTICE
            - ./LICENSE
            - ./CONTRIBUTING.rst
            - ./package.json
            - ./my.conf.js
            - ./app.yaml
            - ./Dockerfile
  deploy_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    docker:
      - image: cimg/openjdk:8.0.302
    working_directory: ~/cananolab
    steps:
      - restore_cache:
          keys:
            - isb-canano-{{ .Branch }}-{{ .Revision }}-
      - install_cloud_sdk
      - deployment_setup
      - auth
      - deployment_config
      - deploy:
          nane: Deployment
          command: |
            sudo -E gcloud app deploy --verbosity=debug ./app.yaml --quiet
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_job
      - deploy_job:
          requires:
            - build_job
          filters:
            branches:
              only:
                - master
                - test
                - uat
                - prod