package gov.nih.nci.cananolab.domain.agentmaterial;
// Generated Oct 17, 2017 2:18:23 PM by Hibernate Tools 4.0.1.Final

import gov.nih.nci.cananolab.domain.particle.ActivationMethod;
import gov.nih.nci.cananolab.domain.particle.ChemicalAssociation;
import gov.nih.nci.cananolab.domain.particle.SampleComposition;
import gov.nih.nci.cananolab.domain.particle.Function;
import java.util.Date;
import java.util.Collection;
import gov.nih.nci.cananolab.domain.common.File;

/**
 * Antibody generated by hbm2java
 */
public class Synthesis extends gov.nih.nci.cananolab.domain.particle.FunctionalizingEntity
		implements java.io.Serializable {

	private String supplierName;
	private String lot;

	public Synthesis() {
	}

	public Synthesis(String createdBy, Date createdDate, String description, String molecularFormula,
			String molecularFormulaType, String name, float value, String valueUnit, String pubChemDataSourceName,
			long pubChemId, Collection<ChemicalAssociation> chemicalAssociationACollection, Collection<ChemicalAssociation> chemicalAssociationBCollection, Collection<File> fileCollection,
			SampleComposition sampleComposition, ActivationMethod activationMethod, Collection<Function> functionCollection,
			String supplier_name, String lot) {
		super(createdBy, createdDate, description, molecularFormula, molecularFormulaType, name, value, valueUnit,
				pubChemDataSourceName, pubChemId, chemicalAssociationACollection, chemicalAssociationBCollection,
				fileCollection, sampleComposition, activationMethod, functionCollection);
		this.supplierName = supplier_name;
		this.lot = lot;
	}

	public String getSupplierName() {
		return this.supplierName;
	}

	public void setLot(String lot) {
		this.lot = lot;
	}

	public String getLot() {
		return this.lot;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}


}
