package gov.nih.nci.cananolab.domain.common;
// Generated Oct 17, 2017 2:18:23 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

//import javax.persistence.CascadeType;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.GeneratedValue;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.JoinTable;
//import javax.persistence.ManyToMany;
//import javax.persistence.Table;

/**
 * File generated by hbm2java
 */
public class File implements java.io.Serializable {

	private Long id;
	private String createdBy;
	private Date createdDate;
	private String description;
	private String name;
	private String title;
	private String type;
	private String uri;
	private Boolean uriExternal;
	private Set<Keyword> keywordCollection = new HashSet<Keyword>(0);
	private Set datumCollection = new HashSet(0);
	private Set findingCollection = new HashSet(0);

	public File() {
	}

	public File(String createdBy, Date createdDate, String description, String name, String title, String type,
			String uri, Boolean uriExternal, Set<Keyword> keywordCollection, Set datumCollection, Set findingCollection) {
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.description = description;
		this.name = name;
		this.title = title;
		this.type = type;
		this.uri = uri;
		this.uriExternal = uriExternal;
		this.keywordCollection = keywordCollection;
		this.datumCollection = datumCollection;
		this.findingCollection = findingCollection;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public Boolean getUriExternal() {
		return this.uriExternal;
	}

	public void setUriExternal(Boolean uriExternal) {
		this.uriExternal = uriExternal;
	}

	public Set<Keyword> getKeywordCollection() {
		return this.keywordCollection;
	}

//	@ManyToMany(cascade = { CascadeType.ALL })
//	@JoinTable(name = "keyword_file", joinColumns = { @JoinColumn(name = "file_pk_id") }, inverseJoinColumns = { @JoinColumn(name = "keyword_pk_id") })
	public void setKeywordCollection(Set<Keyword> keywordCollection) {
		this.keywordCollection = keywordCollection;
	}

	public Set getDatumCollection() {
		return this.datumCollection;
	}

	public void setDatumCollection(Set datumCollection) {
		this.datumCollection = datumCollection;
	}

	public Set getFindingCollection() {
		return this.findingCollection;
	}

	public void setFindingCollection(Set findingCollection) {
		this.findingCollection = findingCollection;
	}

}
