package gov.nih.nci.cananolab.domain.common;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PurityDatum generated by hbm2java
 */
public class PurityDatum implements java.io.Serializable {

	private long datumPkId;
	private File file;
	private Purity purity;
	private String name;
	private Float value;
	private String valueType;
	private String valueUnit;
	private String createdBy;
	private Date createdDate;
	private String numberMod;
	private Set experimentConditions = new HashSet(0);

	public PurityDatum() {
	}

	public PurityDatum(long datumPkId, String name, Float value, String createdBy, Date createdDate) {
		this.datumPkId = datumPkId;
		this.name = name;
		this.value = value;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public PurityDatum(long datumPkId, File file, Purity purity, String name, Float value, String valueType,
			String valueUnit, String createdBy, Date createdDate, String numberMod, Set experimentConditions) {
		this.datumPkId = datumPkId;
		this.file = file;
		this.purity = purity;
		this.name = name;
		this.value = value;
		this.valueType = valueType;
		this.valueUnit = valueUnit;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.numberMod = numberMod;
		this.experimentConditions = experimentConditions;
	}

	public long getId() {
		return this.datumPkId;
	}

	public void setId(long datumPkId) {
		this.datumPkId = datumPkId;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public Purity getPurity() {
		return this.purity;
	}

	public void setPurity(Purity purity) {
		this.purity = purity;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getValue() {
		return this.value;
	}

	public void setValue(Float value) {
		this.value = value;
	}

	public String getValueType() {
		return this.valueType;
	}

	public void setValueType(String valueType) {
		this.valueType = valueType;
	}

	public String getValueUnit() {
		return this.valueUnit;
	}

	public void setValueUnit(String valueUnit) {
		this.valueUnit = valueUnit;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getNumberMod() {
		return this.numberMod;
	}

	public void setNumberMod(String numberMod) {
		this.numberMod = numberMod;
	}

	public Set getConditionCollection() {
		return this.experimentConditions;
	}

	public void setConditionCollection(Set experimentConditions) {
		this.experimentConditions = experimentConditions;
	}

}
