package gov.nih.nci.cananolab.domain.common;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import gov.nih.nci.cananolab.domain.particle.SynthesisMaterialElement;

/**
 * Supplier generated by hbm2java
 */
public class Supplier implements java.io.Serializable {

	private long supplierPkId;
	private SynthesisMaterialElement synthesisMaterialElement;
	private String supplierName;
	private String lot;

	public Supplier() {
	}

	public Supplier(SynthesisMaterialElement synthesisMaterialElement, String supplierName) {
		this.synthesisMaterialElement = synthesisMaterialElement;
		this.supplierName = supplierName;
	}

	public Supplier(SynthesisMaterialElement functionalizingEntity, String supplierName, String lot) {
		this.synthesisMaterialElement = functionalizingEntity;
		this.supplierName = supplierName;
		this.lot = lot;
	}

	public long getId() {
		return this.supplierPkId;
	}

	public void setId(long supplierPkId) {
		this.supplierPkId = supplierPkId;
	}

	public SynthesisMaterialElement getFunctionalizingEntity() {
		return this.synthesisMaterialElement;
	}

	public void setFunctionalizingEntity(SynthesisMaterialElement functionalizingEntity) {
		this.synthesisMaterialElement = functionalizingEntity;
	}

	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getLot() {
		return this.lot;
	}

	public void setLot(String lot) {
		this.lot = lot;
	}

}
